version: '2.4'

services:
  tick:
    image: samuelebistoletti/docker-statsd-influxdb-grafana:latest
    ports:
      - 3003:3003 
      - 3004:8888 
      - 8086:8086 
      - 8125:8125/udp
    ulimits:
      nofile:
        soft: "66000"
        hard: "66000"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - v-grafana:/var/lib/influxdb
    environment:
      - INFLUXDB_URL=http://localhost:8086
      - INFLUX_USERNAME=root
      - INFLUX_PASSWORD=root

  mongodb:
    image: docker.io/mongo:3.6
    networks:
      default:
        aliases:
          - mongodb
    command: mongod --storageEngine wiredTiger --noscripting
    user: mongodb
    volumes:
      - v-ditto-mongo:/data/db
    environment:
       TZ: Europe/Berlin

  policies:
    init: true
    image: docker.io/eclipse/ditto-policies:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1

  things:
    init: true
    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1

  things-search:
    init: true
    image: docker.io/eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1

  concierge:
    init: true
    image: docker.io/eclipse/ditto-concierge:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1

  connectivity:
    init: true
    image: docker.io/eclipse/ditto-connectivity:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
      - concierge
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1

  gateway:
    init: true
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
      - concierge
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - REMOTING_IDLE_CPU_LEVEL=1
      - ENABLE_DUMMY_AUTH=true
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError

  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v3.20.5
    volumes:
       - ./ditto/documentation/src/main/resources/openapi:/usr/share/nginx/html/openapi:ro
       - ./ditto/documentation/src/main/resources/images:/usr/share/nginx/html/images:ro
       - ./swagger3-index.html:/usr/share/nginx/html/index.html:ro
    command: nginx -g 'daemon off;'

  nginx:
    image: docker.io/nginx:1.13-alpine
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
       - ./nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
       - ./index.html:/etc/nginx/html/index.html:ro
       - ./ditto/documentation/src/main/resources/images:/etc/nginx/html/images:ro
    ports:
      - "8080:80"
    depends_on:
      - gateway
volumes:
  v-ditto-mongo:
  v-grafana: